neptune: True
seed: 42
device: 'cuda'

model_path: '/users/scratch1/jbuler/models'
model: "r34"
data:
  fraction_train_rest: 0.75
  fraction_val_test: 0.5
  root_path: '/users/project1/pt01190/mmg'
  metadata_path: '/users/project1/pt01190/mmg/stats_pickle'
  
  view: ['CC', 'MLO']
  size: [7036, 2800]
  # size: [3518, 1400]
  # size: [4588, 1914] # CMMD[2294x1914] [4588, 1914] [2294, 957]
  multimodal: True

  # class_names: ['No metastasis', 'ALNMetastasis']
  # class_names: ['Malignant', 'Lymph_nodes']
  # class_names: ['Normal', 'Benign', 'Malignant', 'Lymph_nodes']
  class_names: ['No cancer', 'Cancer']
  #['Normal', 'Benign', 'Malignant', 'Lymph_nodes'] bcds zmienic 0.1. na 0123
  patch_size: 128
  bag_size_train: -1
  empty_threshold: 0.75
  bag_size_val_test: -1
  overlap_train: 0.5
  overlap_val_test: 0.5

training_plan:
  parameters:
    batch_size: 1
    num_workers: 0
    lr: 0.0005
    wd: 0.001
    epochs: 1000
    patience: 100
    grad_acc_steps: 8

  criterion: 'bce'
  optimizer: 'sgd'

  scheduler:
    name: 'lin'
    step_size: 100
    gamma: 0.9
